# grumphp.yml
# @see https://github.com/phpro/grumphp/tree/master/doc/tasks
parameters:
    bin_dir: "./vendor/bin"
    git_dir: "."
    stop_on_failure: false
    ignore_unstaged_changes: true
    ascii:
        failed: grumphp-grumpy.txt
        succeeded: grumphp-happy.txt
    tasks:
        composer:
          with_dependencies: false
          strict: true
        git_blacklist:
          keywords:
              - "die("
              - "var_dump("
              - "exit;"
              - "print("
              - "print_r("
        git_commit_message:
          matchers:
              - /WSNL-([0-9]+)/
          case_insensitive: false
        jsonlint:
           detect_key_conflicts: true
        phpcsfixer:
          config_file: .php_cs.dist
        phpunit: ~
        xmllint:
          load_from_net: true
          x_include: true
          scheme_validation: true
        yamllint:
          exception_on_invalid_type: true
    extensions: []